### PR TITLE
change fetch_lists function in collect.py

### PR DESCRIPTION
**Pull request by tungdnguyen**
I marked the old fetch list function as deprecated. 

Install dependency by using 

**pip3 install google-api-python-client**

### CODE REVIEW

**Review by aronwc — CHANGES_REQUESTED** [review]
Looking good. Can you please read the api key from the config file? You can see an example here
https://github.com/tapilab/brandelion/blob/master/brandelion/__init__.py

**Comment by tungdnguyen** [comment]
Sure!

**Comment by tungdnguyen** [comment]
I added the config file called "CSE_CFG.ini" and the function read the api keys from it, I'm not sure if this is the way you want it to be done

**Comment by tungdnguyen** [comment]
So does that means the keys are already read in in init.py, then those keys will only be referenced in the collect.py?

**Comment by aronwc** [comment]
Yes.

**Comment by tungdnguyen** [comment]
I hope this is correct, i just referenced the config variable created in __init__.py and assume there's a key already in the config file.

**Comment by aronwc** [comment]
looks good! I'll test it out.

**Pull request merged**
